### ISSUE TITLE
Compilation tag error

### ISSUE THREAD

**Issue by crazyBaboon** [bytebrew/slope#10]
The compilation tag as displayed in the initial main page Github/Slope is wrong. It needs to be re-formatted, since the '  symbols do not show up

**Comment by elvismt** [comment]
A little bit more detail please. What do you mean by compilation tag? Is it the -lslope flag?

**Comment by crazyBaboon** [comment]
it was the characters delimiting `pkg-config --cflags --libs gtk+-3.0`. It 's fine now. Thanks for sorting it out!
