### ISSUE TITLE
Pull request not being handled?

### ISSUE THREAD

**Issue by crazyBaboon** [bytebrew/slope#18]
I have submitted a working example of multianimated plotting stack awhile ago. Have you seen/received this pull request?

**Comment by elvismt** [comment]
I'm sorry, I was occupied with other stuff. Well, your new demo app has animation and multiple plots in a window, and these features are already presented separately in other demos. I prefer to keep the number of demos down to a minimum adding new ones only when new library functionality is added. So, unfortunately I am not going to merge this. Thank you for your contribution, if you look into the library code and implement some new feature it will certainly end up in the master branch.
