### ISSUE TITLE
Cannot see rectangular black line around the legend

### ISSUE THREAD

**Issue by crazyBaboon** [bytebrew/slope#8]
This happens in both devel and master branches. 

I compile and run 'plot_stack.c' in the demos folder. It works fine but I cannot reproduce the black rectangular line around the legends of the plots. I can see, however, the opaque white rectangular box behind the legend text.

**Comment by elvismt** [comment]
The default is now to not show the black stroke. We still have to implement a function to customize it, but the functionality is already there. If you want it change this line 

```c
 priv->rect_stroke_color = SLOPE_COLOR_NULL;
```

to

```c
 priv->rect_stroke_color = SLOPE_COLOR_BLACK;
```

in legend.c.

If you want also implement  `slope_legend_set_stroke_color()` to set it.
